version: '2'
services:
  mysqlDB:
    image: mysql:5.7
    hostname: mysqldb
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=docker
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=dockersystemctl status nginx
      - MYSQL_ROOT_HOST=%
    command:
      [
        'mysqld',
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci',
        '--max-allowed-packet=1G'
      ]
    ports:
      - '3309:3306'
    volumes:
      - /Users/patjawat/Downloads/:/home/
      - ./docker/mysql5.7/data:/var/lib/mysql
      - ./docker/mysql5.7/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  mongoDB:
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=docker
      - MONGO_INITDB_DATABASE=nextjs
      - MONGO_INITDB_USERNAME=patjawat
      - MONGO_INITDB_PASSWORD=112233
    volumes:
      - ./docker/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./docker/mongodb:/data/db

  phpmyadmin_mysql:
    image: phpmyadmin
    restart: always
    links:
      - mysqlDB:db
    ports:
      - 8800:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: docker
      PMA_HOST: mysqlDB
      UPLOAD_LIMIT: 300M